print("#....................................................#")
print("Tugas 1 SISOP Kelas-B")
print(".....................................................")
print("Nama : Adelia Azizatul Haq")
print("NPM : 21083010009")
print(".....................................................")
print("Notes :")
print(".....................................................")
print("Halo Dunia!")
print("Ini adalah script Bash pertamaku di Linux")
print("#....................................................#")
